display_name: SaveX Space

icon: ./assets/images/icon.png

keywords:
  - SaveX Space
  - Clash
  - ClashMeta
  - Proxy

generic_name: SaveX Space

categories:
  - Network

startup_notify: true

include: []